services:
  - type: web
    name: roomers-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false